# Generated by Django 5.1.1 on 2024-09-17 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_article_body_remove_article_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default='jksldgrjgoiejrgejejirojgiewopgjiorjgwepoijrgwgrg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
