# Generated by Django 5.1.1 on 2024-09-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_article_body_article_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lang',
            field=models.CharField(default='title', max_length=10),
            preserve_default=False,
        ),
    ]
