# Generated by Django 5.1.1 on 2024-09-26 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_article_owner_articleuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='owner',
        ),
        migrations.DeleteModel(
            name='ArticleUser',
        ),
        migrations.AddField(
            model_name='article',
            name='owner',
            field=models.ManyToManyField(related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
